---
## General pipeline parameters:
tutorialText: TRUE

## Pipeline-specific parameters
threads: 50
pychopper: TRUE

# Input genome:
genome_fasta: "http://ftp.ensembl.org/pub/release-94/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz"
genome_annot: "http://ftp.ensembl.org/pub/release-94/gff3/homo_sapiens/Homo_sapiens.GRCh38.94.chromosome.20.gff3.gz"
# genome_fasta could either be (1) a URL to a genome assembly e.g. at enseml / ncbi
#                              (2) a filename corresponding to file that has been placed in the $ReferenceData folder

# CDNA or direct RNA reads in fastq format:
raw_fastq: "NA12878-cDNA-1D.chr20.filt.fastq.bz2"


# Extra option passed to minimap2 when generating index:
minimap_index_opts: "-k14"

# Extra options passed to minimap2:
#minimap2_opts: ""
# Enable this for stranded data:
minimap2_opts: "-uf"

# Minmum mapping quality:
minimum_mapping_quality: 10

# Options passed to spliced_bam2gff:
#spliced_bam2gff_opts: ""
# Enable this for stranded data:
spliced_bam2gff_opts: "-s"

# -c parameter:
minimum_cluster_size: 10

# -p parameter:
minimum_isoform_percent: 1.0

# -d parameter:
exon_boundary_tolerance: 10

# -e parameter:
terminal_exon_boundary_tolerance: 30

# Extra options passed to minimap2 when mapping polished reads:
#minimap2_opts_polished: ""
# Enable this for stranded data:
minimap2_opts_polished: "-uf"
# Enable this for SIRV data:
#minimap2_opts_polished: "--splice-flank=no"

# Options passed to spliced_bam2gff when converting alignments of polished reads:
#spliced_bam2gff_opts_pol: ""
# Enable this for stranded data:
spliced_bam2gff_opts_pol: "-s"

# Options passed to collapse_partials when collapsing fragmentation artifacts
# in clustered and polished transcripts.

# Internal exon boundary tolerance:
collapse_internal_tol: 5

# Five prime boundary tolerance:
collapse_five_tol: 5000

# Three prime boundary tolerance:
collapse_three_tol: 30

